# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f05cf40d4baee814c3d0678027f6f1a982bad2acc862e7718f2ce695bc64ac1caf8fdc4056f5c497ea71048c62b14601516c3ee2be2d2a608c73ebbe72fbc8

test:
  secret_key_base: 9a250bcc7fbb685e27b3a299a322a6029326080fa008017899665935ab8084dc1e90a68e9d9d178d547336b3378469b051973e36dbfc628ec97905548538d6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
